[project]
name = "wave-hive"
authors = []
description = ""
telemetry = false
requirements = []
[contracts.wave_hive]
path = "contracts/wave_hive.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
